name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: go-eat-it.vercel.app
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
        env:
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
          NEXT_PUBLIC_GRAPHCMS_ENDPOINT: ${{ secrets.NEXT_PUBLIC_GRAPHCMS_ENDPOINT }}
      - name: Deploy to Vercel (Prod)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
      - name: Notify Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          args: "✅ *Production deployed!*"
