name: Reusable Build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "22"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "GRAPHCMS_TOKEN=${{ secrets.GRAPHCMS_TOKEN }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_GRAPHCMS_ENDPOINT=${{ secrets.NEXT_PUBLIC_GRAPHCMS_ENDPOINT }}" >> $GITHUB_ENV

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build
